# Generated by Django 5.2.10 on 2026-02-10 15:14

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 4), ('highlight', 6), ('featured_news', 7), ('cta', 9), ('divider', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2), ('cta_text', 1), ('cta_url', 3)]], {}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 5)]], {}), 7: ('home.blocks.FeaturedNewsBlock', (), {}), 8: ('wagtail.blocks.URLBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('text', 0), ('button_text', 0), ('button_url', 8)]], {}), 10: ('home.blocks.DividerBlock', (), {})}, default=list)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Id', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=250)),
                ('body', wagtail.fields.StreamField([('text', 0), ('image', 3), ('gallery', 4), ('video', 5), ('two_columns', 7), ('features', 8), ('testimonial', 11), ('highlight', 12), ('cta', 14), ('divider', 15), ('section', 16)], blank=True, block_lookup={0: ('home.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {}), 4: ('home.blocks.GalleryBlock', (), {}), 5: ('home.blocks.VideoEmbedBlock', (), {}), 6: ('wagtail.blocks.RichTextBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('left', 6), ('right', 6)]], {}), 8: ('home.blocks.FeaturesBlock', (), {}), 9: ('wagtail.blocks.TextBlock', (), {}), 10: ('wagtail.blocks.CharBlock', (), {}), 11: ('wagtail.blocks.StructBlock', [[('quote', 9), ('author', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('title', 10), ('text', 9)]], {}), 13: ('wagtail.blocks.URLBlock', (), {}), 14: ('wagtail.blocks.StructBlock', [[('text', 10), ('button_text', 10), ('button_url', 13)]], {}), 15: ('home.blocks.DividerBlock', (), {}), 16: ('wagtail.blocks.StreamBlock', [[]], {})}, default=list)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_title', models.CharField(blank=True, help_text='Texto del enlace', max_length=50)),
                ('link_url', models.CharField(blank=True, help_text='URL externa (ej: https://google.com)', max_length=500)),
                ('open_in_new_tab', models.BooleanField(blank=True, default=False)),
                ('link_page', models.ForeignKey(blank=True, help_text='O selecciona una página interna', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='home.menu')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
